### ISSUE TITLE
Effects Persist Indefinitely After Death in Both 5.2 and 5.3-dev, Singleplayer and Multiplayer

### ISSUE THREAD

**Issue by ApothecaryOfLight** [appgurueu/magic_potions#1]
I am using most recent github repositories for magic_potions, modlib and hud_timers. I tried both 5.2 stable and 5.3-dev, and tried it in multiplayer and singleplayer in a fresh Minetest default game installation.

All effects that are current when the player dies remain in effect on respawn, and remain in effect indefinitely. The timers are correctly destroyed and their destruction is recorded in hud_timer's log.

I was able to fix the issue by adding to the **def.on_use** block an additional **timer.on_remove** with the same code as the existing **timer.on_complete**.

```
timer.on_complete = function(playername)
  local player_data = players[playername]
  player_data.timers[timer] = nil
  player_data.in_use = player_data.in_use - 1
  potion_def.reverse(playername, gain)
end
```
I changed the above code into the code below to fix the problem.

```
timer.on_complete = function(playername)
  local player_data = players[playername]
  player_data.timers[timer] = nil
  player_data.in_use = player_data.in_use - 1
  potion_def.reverse(playername, gain)
end
timer.on_remove = function(playername)
  timer.on_complete(playername)
end
```

**Comment by appgurueu** [comment]
Ah yes, [somewhen](https://github.com/appgurueu/hud_timers/commit/4d31b19c7358024abd8bcc8b45a04463a69e73e4) I decided to separate `on_complete` and `on_remove`... Fixed this in a fashion similar to your suggestion, using [`timer.on_remove = timer.on_complete`](https://github.com/appgurueu/magic_potions/commit/6c97ec50cbafaf1c6bc1ea86b8a2fa0340329e12)

Thanks for reporting!

**Comment by ApothecaryOfLight** [comment]
No problem! Thanks for making the mod!
